name: membrane-curvature
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - sphinx
     # Testing
  - pytest
  - pytest-cov
  - codecov
  - MDAnalysisTests

    # Pip-only installs
  - pip:
    - MDAnalysis==2.0.0b0
