version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
    cooldown:
      default-days: 7
    groups:
      all-actions:
        patterns: [ "*" ]

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
    groups:
      production:
        patterns: ["*"]
        dependency-type: "production"
      development:
        patterns: ["*"]
        dependency-type: "development"
    ignore:
      - dependency-name: "nglview"

  - package-ecosystem: "conda"
    directory: "/devtools/conda-envs"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:00"
    groups:
      all-conda:
        patterns: ["*"]
