# readthedocs.yml

version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  post_install:
      - python -m ipykernel install --name mc_docs --display-name "mc_docs"

python:
  install:
    - method: pip
      path: .

conda:
  environment: docs/requirements.yaml
