name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - MDAnalysis
  - ipython
  - MDAnalysisTests
  - sphinx_rtd_theme
    # Pip-only installs
  - pip:
    - nbsphinx
    - ipywidgets
    - nglview