name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - MDAnalysis
  - MDAnalysisData
  - networkx # LeafletFinder dependency
  - tidynamics # MSD dependency
  - ipython
  - MDAnalysisTests
  - mdanalysis-sphinx-theme>=1.3.0
    # Pip-only installs
  - pip:
    - myst-nb
    - pickleshare # ipython savefigs
    - ipywidgets
    - nglview
