name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - ipython

    # Pip-only installs
  - pip:
    - MDAnalysis==2.0.0b0
    - MDAnalysisTests

