name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # 3 am Tuesdays and Fridays
    - cron: "0 3 * * 2,5"

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true


jobs:
  test:
    name: "Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10"]
        env_file: [env, ]
        include:
          - name: minimum_requirements
            os: ubuntu-latest
            python-version: 3.8
            env_file: min

    steps:
    - uses: actions/checkout@v3

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    # More info on options: https://github.com/conda-incubator/setup-miniconda
    # An environment for the minimum versions 
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/test_${{ matrix.env_file }}.yaml
        channels: conda-forge, defaults
        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    
    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list

    - name: Run tests
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        pytest -v --cov=membrane_curvature --cov-report=xml --color=yes membrane_curvature/tests/

    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        fail_ci_if_error: True

  upstream_develop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        latest-python : ["3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.latest-python }}

    - name:  pip install membrane-curvature
      run: |
        pip install git+https://github.com/MDAnalysis/mdanalysis.git@develop#subdirectory=package
        python -m pip install .

    - name: install pytest
      run: |
        python -m pip install pytest

    - name: run tests
      run: |
        pytest --disable-pytest-warnings membrane_curvature/tests/
